import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-100 h-screen justify-center items-center bg-indigo-800 text-5xl text-yellow-50">
        Deneme
      </div>
    </div>
  );
}
